// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNxdx8u_x-ozh5E_3IF5OTEWJmjmbYzFg',
    appId: '1:679716986260:web:f54d0e397f25afe1f00381',
    messagingSenderId: '679716986260',
    projectId: 'smartsplit-87a0b',
    authDomain: 'smartsplit-87a0b.firebaseapp.com',
    storageBucket: 'smartsplit-87a0b.firebasestorage.app',
    measurementId: 'G-Y8GJNWWHWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz62j4nMWgEI1s8vsbzj4GDnK3suklJ44',
    appId: '1:679716986260:android:6c21db4fe650ea2ff00381',
    messagingSenderId: '679716986260',
    projectId: 'smartsplit-87a0b',
    storageBucket: 'smartsplit-87a0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6VRQqJthg0iSolF1SzmZi-QP6QWdYxNE',
    appId: '1:679716986260:ios:9d310f787b1b694ff00381',
    messagingSenderId: '679716986260',
    projectId: 'smartsplit-87a0b',
    storageBucket: 'smartsplit-87a0b.firebasestorage.app',
    iosBundleId: 'com.example.smartsplitclient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6VRQqJthg0iSolF1SzmZi-QP6QWdYxNE',
    appId: '1:679716986260:ios:9d310f787b1b694ff00381',
    messagingSenderId: '679716986260',
    projectId: 'smartsplit-87a0b',
    storageBucket: 'smartsplit-87a0b.firebasestorage.app',
    iosBundleId: 'com.example.smartsplitclient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNxdx8u_x-ozh5E_3IF5OTEWJmjmbYzFg',
    appId: '1:679716986260:web:4b2601aabfb0d17df00381',
    messagingSenderId: '679716986260',
    projectId: 'smartsplit-87a0b',
    authDomain: 'smartsplit-87a0b.firebaseapp.com',
    storageBucket: 'smartsplit-87a0b.firebasestorage.app',
    measurementId: 'G-JK4D3WR3F9',
  );
}